server:
  http_listen_port: 9080  # Port for Promtail's API

positions:
  filename: /tmp/positions.yaml  # Track last read log position

clients:
  - url: "http://loki:3100/loki/api/v1/push"  # Loki's endpoint

scrape_configs:
  - job_name: "docker-logs"
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"  # Read logs from Docker
        refresh_interval: 5s  # Refresh container list

    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        target_label: "container"  # Label logs by container name
      - source_labels: ["__meta_docker_container_id"]
        target_label: "container_id"

    pipeline_stages:
      - json:
          expressions:
            stream: "stream"
            log: "log"
      - labels:
          stream: ""
